[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python run_bot.py"
# Force rebuild - 2026-02-02-13-01-00-POSTGRESQL-TOOLS

[[services]]
name = "music-legends-bot"

[services.variables]
PYTHON_VERSION = "3.11"
